services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cs2utils
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql 
      - ./src/backend/src/main/resources/db/migration/V1__create_map_table.sql:/docker-entrypoint-initdb.d/init.sql
 
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/cs2utils
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=secret
      - ASSETS_PATH=/app/assets
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src/backend/src/main/assets:/app/assets
 
  frontend:
    build:
      context: src/frontend/cs2Utils
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:4200

volumes:
  pgdata: